baseURL = "https://fl-sean03.github.io/"
languageCode = "en-us"
title = "Sean Florez"

[params]
  description = "Materials scientist building the bridge between atomic-level understanding and real-world deployment."
  author = "Sean P. Florez"
  email = "sean.florez@colorado.edu"
  linkedin = "https://linkedin.com/in/sean-florez"
  github = "https://github.com/fl-sean03"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writings"
    url = "/writings/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
